#ifndef _INCLUDE_HPCSTYPE_HPP_
#define _INCLUDE_HPCSTYPE_HPP_

typedef enum {
	HPCS_SUCCESS = 0,
	HPCS_MALLOC_MEMORY_FAILED = -1,
	HPCS_PARAM_ERROR = -2,

	HPCS_FILE_OPEN_FAILED = -10,
	HPCS_FILE_READ_FAILED = -11,
	HPCS_FILE_WRITE_FAILED = -12,
	HPCS_FILE_GET_STATUS_FAILED = -13,
	HPCS_FILE_FORMAT_INVALID = -14

} HPCsStatus;

#endif
